# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: mypool
  agent: WJLP-1800

variables:
- group: demo-vg

steps:
- checkout: none
- script: echo Hello, world!
  displayName: 'Run a one-line script'
- script: echo "Using variable from variable group $(variable1)"
  displayName: 'Print Variable'
- script: echo "Using variable from variable group $(secret1)"
  displayName: 'Print Variable'