name: Build and deploy Angular app to an Azure Web App

on:
#   push:
#     branches:
#       - master

  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true

env:
  NODE_VERSION: '16.x'           # set this to the node version to use

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: "npm"
        cache-dependency-path: package-lock.json
        
    - name: dev build
      run: echo "Dev Build"
  

  deployDev:
    name: Deploy to Dev
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "Development"
      url: ${ { steps.deploy-to-webapp.outputs.webapp-url } }

    steps:
      - name: dev build
        run: echo "Deploy Development"
        
  build-staging:
    name: Build-staging
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: "npm"
        cache-dependency-path: package-lock.json
        
    - name: staging build
      run: echo "Staging Build"
  
  deployStaging:
    name: Deploy to Staging
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build-staging
    environment:
      name: "Staging"
      url: ${ { steps.deploy-to-webapp-prod.outputs.webapp-url } }

    steps:
      - name: staging deploy
        env:
          ENV: ${{ vars.ENV }}
          ENV_SECRET: ${{ secrets.ENV_SECRET }}
        run: |
          echo "Deploy Staging"
          echo $ENV
          echo $ENV_SECRET

  build-prod:
    name: Build-prod
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: "npm"
        cache-dependency-path: package-lock.json
        
    - name: prod build
      run: echo "Prod Build"
  
  deployProd:
    name: Deploy to Production
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build-prod
    environment:
      name: "Production"
      url: ${ { steps.deploy-to-webapp-prod.outputs.webapp-url } }

    steps:
      - name: prod deploy
        env:
          ENV: ${{ vars.ENV }}
          ENV_SECRET: ${{ secrets.ENV_SECRET }}
        run: |
          echo "Deploy Production"
          echo $ENV
          echo $ENV_SECRET
